interfaces {
	et-0/0/6 {
		mtu 9216;
		replace: unit 0 {
			family inet {
				unnumbered-address lo0.1;
			}
			family inet6;
			family iso;
		}
	}
	et-0/0/12 {
		mtu 9216;
		replace: unit 0 {
			family inet {
				unnumbered-address lo0.1;
			}
			family inet6;
			family iso;
		}
	}
	et-0/0/14 {
		mtu 9216;
		replace: unit 0 {
			family inet {
				unnumbered-address lo0.1;
			}
			family inet6;
			family iso;
		}
	}
	lo0 {
		unit 1 {
			family inet {
				address 10.0.0.1/32;
			}
			family inet6 {
				address fc00:0:1::1/128;
			}
			family iso {
				address 49.0001.0000.0000.0001.00;
			}
		}
	}
}

routing-instances {
	cluster {
		instance-type virtual-router;
		interface et-0/0/6.0;
		interface et-0/0/12.0;
		interface et-0/0/14.0;
		interface lo0.1;
		routing-options {
			router-id 10.0.0.1;
		}
		protocols {
			isis {
				level 2 disable;
				level 1 wide-metrics-only;
				topologies ipv6-unicast;
				replace: interface et-0/0/6.0 {
					point-to-point;
					level 1 metric 10;
				}
				replace: interface et-0/0/12.0 {
					point-to-point;
					level 1 metric 10;
				}
				replace: interface et-0/0/14.0 {
					point-to-point;
					level 1 metric 10;
				}
				replace: interface lo0.1 {
					passive;
					level 1 metric 0;
				}
			}
		}
	}
}
