log file /etc/frr/frr.log debug

debug zebra events
debug bgp zebra
debug bgp updates
debug bgp neighbor-events
!
interface sno-labbm
 ipv6 router isis PE
exit
!
interface lo-und
 ipv6 router isis PE
 isis passive
exit
!
router bgp 65500
 bgp router-id 10.0.0.20
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 no bgp network import-check
 bgp log-neighbor-changes
 !
 neighbor PE-NODES peer-group
 neighbor PE-NODES capability extended-nexthop
 neighbor PE-NODES remote-as 65500
 neighbor PE-NODES update-source fc00:0:20::1
 neighbor fc00:0:2::1 peer-group PE-NODES
 neighbor fd00::2 peer-group PE-NODES
 neighbor fc00:0:3::1 peer-group PE-NODES
 neighbor fd00::3 peer-group PE-NODES
 neighbor fc00:0:4::1 peer-group PE-NODES
 neighbor fd00::4 peer-group PE-NODES
 neighbor fc00:0:5::1 peer-group PE-NODES
 neighbor fd00::5 peer-group PE-NODES
 neighbor fc00:0:6::1 peer-group PE-NODES
 neighbor fd00::6 peer-group PE-NODES
 !
 segment-routing srv6
  locator MAIN
  encap-behavior H_Encaps_Red
 exit
 !
 address-family ipv4 vpn
  neighbor PE-NODES activate
 exit-address-family
 !
 address-family ipv6 vpn
  neighbor PE-NODES activate
 exit-address-family
exit
!
router bgp 65500 vrf red
 bgp router-id 10.0.0.20
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 no bgp network import-check
 sid vpn per-vrf export auto
 !
 address-family ipv4 unicast
  network 10.10.20.1/32
  network 10.100.0.1/32
  rd vpn export 10.0.0.20:2
  rt vpn both 65500:2
  export vpn
  import vpn
 exit-address-family
 !
 address-family ipv6 unicast
  network fc00:10:20::1/128
  rd vpn export 10.0.0.20:2
  rt vpn both 65500:2
  export vpn
  import vpn
 exit-address-family
exit
!
router isis PE
 is-type level-1
 net 49.0001.0000.0000.0020.00
 lsp-gen-interval 2
 log-adjacency-changes
 log-pdu-drops
 segment-routing srv6
  locator MAIN
 exit
exit
!
segment-routing
 srv6
  encapsulation
   source-address fd00:20::1
  exit
  locators
   locator MAIN
    prefix fd00:20::/48 block-len 32 node-len 16 func-bits 16
    behavior usid
   exit
  exit
 exit
exit
!
end
