#!/bin/bash
set -euo pipefail

# setup-underlay.sh - Set up underlay infrastructure for flat ISIS routing
#
# This script:
# 1. Waits for FRR container to be ready
# 2. Derives router-id and ISIS NET from host VF2 or br-ex last octet
# 3. Moves underlay NIC (VF0) and trunk NIC (VF1) to FRR namespace
# 4. Creates VLAN 42 sub-interface on VF1
# 5. Saves variables for config generation
#
# Usage: Executed by systemd service setup-underlay.service

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ ! -f "$SCRIPT_DIR/openperouter-common.sh" ]]; then
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] ERROR: openperouter-common.sh not found at $SCRIPT_DIR/openperouter-common.sh" >&2
    exit 1
fi

source "$SCRIPT_DIR/openperouter-common.sh"

for func in frr_netns_pid inns isfrr_ready; do
    if ! declare -f "$func" >/dev/null 2>&1; then
        echo "[$(date +'%Y-%m-%d %H:%M:%S')] ERROR: Required function $func not found in openperouter-common.sh" >&2
        exit 1
    fi
done

UNDERLAY_NIC="${UNDERLAY_NIC:-ens1f0v0}"
TRUNK_NIC="${TRUNK_NIC:-ens1f0v1}"
FRR_READY_TIMEOUT="${FRR_READY_TIMEOUT:-60}"
NODE_NAME="${NODE_NAME:-$(hostname)}"

VARS_FILE="${VARS_FILE:-/var/lib/openperouter/vpn-setup.vars}"

ISIS_AREA="${ISIS_AREA:-49.0001}"

log "Starting underlay setup (flat / ISIS routing mode)"
log "Configuration: UNDERLAY_NIC=$UNDERLAY_NIC, TRUNK_NIC=$TRUNK_NIC, NODE_NAME=$NODE_NAME"

#
# STEP 1: Wait for FRR container to be ready
#
log_step "Waiting for FRR container"
log "Timeout configured: ${FRR_READY_TIMEOUT}s"
ELAPSED=0
INTERVAL=2

while ! isfrr_ready 2>/dev/null; do
    if [ $ELAPSED -ge $FRR_READY_TIMEOUT ]; then
        error "FRR not ready after ${FRR_READY_TIMEOUT}s timeout"
        exit_timeout
    fi
    if [ $((ELAPSED % 10)) -eq 0 ] && [ $ELAPSED -gt 0 ]; then
        log "Still waiting for FRR... (${ELAPSED}s elapsed)"
    fi
    sleep $INTERVAL
    ELAPSED=$((ELAPSED + INTERVAL))
done

log "FRR container is ready"

#
# STEP 2: Derive addressing from VF2 (or br-ex after OVS takes over)
#
log_step "Deriving addressing from host interface"

HOST_VF="${HOST_VF:-ens1f0v2}"
HOST_IP_TIMEOUT="${HOST_IP_TIMEOUT:-120}"
HOST_ELAPSED=0
HOST_INTERVAL=2
HOST_IP=""
HOST_IFACE=""

while [[ -z "$HOST_IP" ]]; do
    for iface in "$HOST_VF" br-ex; do
        if ip link show "$iface" >/dev/null 2>&1; then
            HOST_IP=$(ip -j -4 addr show "$iface" 2>/dev/null | jq -r '.[0].addr_info[0].local // empty')
            if [[ -n "$HOST_IP" ]]; then
                HOST_IFACE="$iface"
                break
            fi
        fi
    done
    if [[ -n "$HOST_IP" ]]; then
        break
    fi
    if [ $HOST_ELAPSED -ge $HOST_IP_TIMEOUT ]; then
        error "No host interface ($HOST_VF/br-ex) has an IP after ${HOST_IP_TIMEOUT}s"
        exit_error "Host interface must have an IP address configured"
    fi
    if [ $((HOST_ELAPSED % 10)) -eq 0 ] && [ $HOST_ELAPSED -gt 0 ]; then
        log "Waiting for host IP address... (${HOST_ELAPSED}s elapsed)"
    fi
    sleep $HOST_INTERVAL
    HOST_ELAPSED=$((HOST_ELAPSED + HOST_INTERVAL))
done

LAST_OCTET=$(echo "$HOST_IP" | cut -d. -f4)

# Router-id and ISIS NET derived from last octet
ROUTER_ID="10.0.0.${LAST_OCTET}"
ISIS_NET=$(printf '%s.0000.0000.%04d.00' "$ISIS_AREA" "$LAST_OCTET")

# Cluster gateway IPs (anycast across all nodes)
GATEWAY_IP="192.168.110.1/24"
GATEWAY_IP_V6="fd00:110::1/64"

log "Host interface: $HOST_IFACE, IP: $HOST_IP"
log "Node index (last octet): $LAST_OCTET"
log "  Router-ID:  $ROUTER_ID"
log "  ISIS NET:   $ISIS_NET"
log "  Gateway IPv4: $GATEWAY_IP"
log "  Gateway IPv6: $GATEWAY_IP_V6"

FRR_PID=$(frr_netns_pid)
if [[ -z "$FRR_PID" || "$FRR_PID" == "0" ]]; then
    error "Failed to get FRR container PID"
    exit_error "Cannot determine FRR namespace"
fi

log "FRR container PID: $FRR_PID"

UNDERLAY_PCI=$(cut -d' ' -f3 /run/grout-bind/$UNDERLAY_NIC) ||
    exit_error "Failed to determine underlay VF $UNDERLAY_NIC PCI address"
TRUNK_PCI=$(cut -d' ' -f3 /run/grout-bind/$TRUNK_NIC) ||
    exit_error "Failed to determine trunk VF $TRUNK_NIC PCI address"

TRUNK_VLAN="${TRUNK_NIC}.42"

grcli() {
    echo "+ grcli $*"
    podman exec grout grcli "$@"
}

log "Applying grout configuration..."

grcli interface add port $UNDERLAY_NIC devargs $UNDERLAY_PCI
grcli interface add port $TRUNK_NIC devargs $TRUNK_PCI
grcli interface add vlan $TRUNK_VLAN parent $TRUNK_NIC vlan_id 42

log "$UNDERLAY_NIC and $TRUNK_VLAN configured"

#
# STEP 6: Save variables for config generation
#
log_step "Saving variables for config generation"

mkdir -p "$(dirname "$VARS_FILE")"

cat > "$VARS_FILE" <<EOF
# OpenPERouter VPN Setup Variables (flat / ISIS routing)
# Generated by setup-underlay.sh on $(date +'%Y-%m-%d %H:%M:%S')

# Node identity
NODE_NAME="$NODE_NAME"
LAST_OCTET="$LAST_OCTET"
ROUTER_ID="$ROUTER_ID"
ISIS_NET="$ISIS_NET"

# Host IPs (OCP cluster addresses)
HOST_IP="$HOST_IP"

# Underlay and trunk NICs
UNDERLAY_NIC="$UNDERLAY_NIC"
TRUNK_NIC="$TRUNK_NIC"
TRUNK_VLAN="$TRUNK_VLAN"
FRR_PID="$FRR_PID"

# Gateway IPs (anycast, on trunk VLAN sub-interface)
GATEWAY_IP="$GATEWAY_IP"
GATEWAY_IP_V6="$GATEWAY_IP_V6"
EOF

chmod 644 "$VARS_FILE"

log "Variables saved to $VARS_FILE"

exit_success "Underlay setup completed successfully"
