apiVersion: v1alpha1
metadata:
  name: sno-lab
  namespace: cluster0
additionalNTPSources:
- 10.100.0.1
rendezvousIP: 192.168.110.2
hosts:
- hostname: master-0
  interfaces:
  - name: ens3f0np0
    macAddress: B8:E9:24:16:09:AC
  - name: eno12399np0
    macAddress: B8:E9:24:8F:D8:B6
  networkConfig:
    interfaces:
    - name: br0
      type: linux-bridge
      state: up
      mtu: 1400
      ipv4:
        enabled: true
        auto-dns: false
        address:
        - ip: 192.168.110.2
          prefix-length: 24
        dhcp: false
      ipv6:
        enabled: true
        auto-dns: false
        address:
        - ip: fd00:110::2
          prefix-length: 64
        dhcp: false
      bridge:
        port:
        - name: dummy0
    - name: dummy0
      type: dummy
      state: up
      ipv4:
        enabled: false
      ipv6:
        enabled: false

#    - name: macvl0
#      type: mac-vlan
#      state: up
#      mac-vlan:
#              #base-iface: bond0
#        base-iface: eno12399np0
#        mode: passthru
#      ipv4:
#        enabled: true
#        address:
#          - ip: 192.168.132.20
#            prefix-length: 25
#        dhcp: false
#      ipv6:
#        enabled: true
#        address:
#        - ip: 2600:52:7:132::20
#          prefix-length: 64
#        dhcp: false
#    - name: bond0
#      type: bond
#      state: up
#      ipv4:
#        enabled: false
#      ipv6:
#        enabled: false
#      link-aggregation:
#        mode: 802.3ad
#        options: {"miimon": 100}
#        ports:
#          - eno12399np0
#          - eno12409np1
    - name: eno12399np0
      state: up
      type: ethernet
      ipv4:
        enabled: true
        address:
          - ip: 192.168.135.21
            prefix-length: 25
        dhcp: false
      ipv6:
        enabled: true
        address:
        - ip: 2600:52:7:135::21
          prefix-length: 64
        dhcp: false
    - name: eno12409np1
      state: down
      type: ethernet

    - name: bond1
      state: down
      type: bond
      link-aggregation:
        mode: 802.3ad
        options: {"miimon": 100}
        ports:
          - ens3f0np0
          - ens3f1np1
    - name: ens3f0np0
      state: down
      type: ethernet
    - name: ens3f1np1
      state: down
      type: ethernet
    - name: bond1.16
      state: up
      type: vlan
      wait-ip: ipv4
      ipv4:
        address:
          - ip: 192.168.21.31
            prefix-length: 25
        dhcp: false
        enabled: true
      vlan:
        base-iface: bond1
        id: 16

    dns-resolver:
      config:
        server:
        - 192.168.110.1
        - fd00:110::1
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 192.168.110.1
        next-hop-interface: br0
        table-id: 254
      - destination: ::/0
        next-hop-address: fd00:110::1
        next-hop-interface: br0
        table-id: 254
- hostname: master-1
  interfaces:
  - name: ens3f0np0
    macAddress: B8:E9:24:16:0E:0C
  - name: eno12399np0
    macAddress: B8:E9:24:8F:DB:EC
  networkConfig:
    interfaces:
    - name: br0
      type: linux-bridge
      state: up
      mtu: 1400
      ipv4:
        enabled: true
        auto-dns: false
        address:
          - ip: 192.168.110.3
            prefix-length: 24
        dhcp: false
      ipv6:
        enabled: true
        auto-dns: false
        address:
        - ip: fd00:110::3
          prefix-length: 64
        dhcp: false
      bridge:
        port:
        - name: dummy0
    - name: dummy0
      type: dummy
      state: up
      ipv4:
        enabled: false
      ipv6:
        enabled: false

#    - name: macvl0
#      type: mac-vlan
#      state: up
#      mac-vlan:
#        base-iface: bond0
#        mode: passthru
#      ipv4:
#        enabled: true
#        address:
#          - ip: 192.168.132.21
#            prefix-length: 25
#        dhcp: false
#      ipv6:
#        enabled: true
#        address:
#        - ip: 2600:52:7:132::21
#          prefix-length: 64
#        dhcp: false
#    - name: bond0
#      state: up
#      type: bond
#      ipv4:
#        enabled: false
#      ipv6:
#        enabled: false
#      link-aggregation:
#        mode: 802.3ad
#        options: {"miimon": 100}
#        ports:
#          - eno12399np0
#          - eno12409np1
    - name: eno12399np0
      state: up
      type: ethernet
      ipv4:
        enabled: true
        address:
          - ip: 192.168.136.22
            prefix-length: 25
        dhcp: false
      ipv6:
        enabled: true
        address:
        - ip: 2600:52:7:136::22
          prefix-length: 64
        dhcp: false
    - name: eno12409np1
      state: down
      type: ethernet

    - name: bond1
      state: down
      type: bond
      link-aggregation:
        mode: 802.3ad
        options: {"miimon": 100}
        ports:
          - ens3f0np0
          - ens3f1np1
    - name: ens3f0np0
      state: down
      type: ethernet
    - name: ens3f1np1
      state: down
      type: ethernet
    - name: bond1.16
      state: up
      type: vlan
      wait-ip: ipv4
      ipv4:
        address:
          - ip: 192.168.21.32
            prefix-length: 25
        dhcp: false
        enabled: true
      vlan:
        base-iface: bond1
        id: 16

    dns-resolver:
      config:
        server:
        - 192.168.110.1
        - fd00:110::1
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 192.168.110.1
        next-hop-interface: br0
        table-id: 254
      - destination: ::/0
        next-hop-address: fd00:110::1
        next-hop-interface: br0
        table-id: 254
- hostname: master-2
  interfaces:
  - name: ens3f0np0
    macAddress: B8:E9:24:16:09:84
  - name: eno12399np0
    macAddress: B8:E9:24:8F:D8:AE
  networkConfig:
    interfaces:
    - name: br0
      type: linux-bridge
      state: up
      mtu: 1400
      ipv4:
        enabled: true
        auto-dns: false
        address:
          - ip: 192.168.110.4
            prefix-length: 24
        dhcp: false
      ipv6:
        enabled: true
        auto-dns: false
        address:
        - ip: fd00:110::4
          prefix-length: 64
        dhcp: false
      bridge:
        port:
        - name: dummy0
    - name: dummy0
      type: dummy
      state: up
      ipv4:
        enabled: false
      ipv6:
        enabled: false
#
#    - name: macvl0
#      type: mac-vlan
#      state: up
#      mac-vlan:
#        base-iface: bond0
#        mode: passthru
#      ipv4:
#        enabled: true
#        address:
#          - ip: 192.168.132.22
#            prefix-length: 25
#        dhcp: false
#      ipv6:
#        enabled: true
#        address:
#        - ip: 2600:52:7:132::22
#          prefix-length: 64
#        dhcp: false
#    - name: bond0
#      state: up
#      type: bond
#      ipv4:
#        enabled: false
#      ipv6:
#        enabled: false
#      link-aggregation:
#        mode: 802.3ad
#        options: {"miimon": 100}
#        ports:
#          - eno12399np0
#          - eno12409np1
    - name: eno12399np0
      state: up
      type: ethernet
      ipv4:
        enabled: true
        address:
          - ip: 192.168.137.23
            prefix-length: 25
        dhcp: false
      ipv6:
        enabled: true
        address:
        - ip: 2600:52:7:137::23
          prefix-length: 64
        dhcp: false
    - name: eno12409np1
      state: down
      type: ethernet

    - name: bond1
      state: down
      type: bond
      link-aggregation:
        mode: 802.3ad
        options: {"miimon": 100}
        ports:
          - ens3f0np0
          - ens3f1np1
    - name: ens3f0np0
      state: down
      type: ethernet
    - name: ens3f1np1
      state: down
      type: ethernet
    - name: bond1.16
      state: up
      type: vlan
      wait-ip: ipv4
      ipv4:
        address:
          - ip: 192.168.21.33
            prefix-length: 25
        dhcp: false
        enabled: true
      vlan:
        base-iface: bond1
        id: 16

    dns-resolver:
      config:
        server:
        - 192.168.110.1
        - fd00:110::1
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 192.168.110.1
        next-hop-interface: br0
        table-id: 254
      - destination: ::/0
        next-hop-address: fd00:110::1
        next-hop-interface: br0
        table-id: 254
