apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: grout-performance
spec:
  cpu:
    reserved: "0-19"
    isolated: "20-191"
  hugepages:
    defaultHugepagesSize: 1G
    pages:
    - count: 32
      size: 1G
      node: 0
  numa:
    topologyPolicy: single-numa-node
  workloadHints:
    highPowerConsumption: false
    realTime: true
    perPodPowerManagement: false
  additionalKernelArgs:
    - iommu=pt
    - intel_iommu=on
  nodeSelector:
    node-role.kubernetes.io/master: ""
