listen-address=10.100.0.1
listen-address=fd00:100::1
bind-interfaces
no-resolv
no-hosts
local=/sno-lab.example.com/
address=/api.sno-lab.example.com/192.168.110.10
address=/api.sno-lab.example.com/fd00:110::10
address=/api-int.sno-lab.example.com/192.168.110.10
address=/api-int.sno-lab.example.com/fd00:110::10
address=/.apps.sno-lab.example.com/192.168.110.11
address=/.apps.sno-lab.example.com/fd00:110::11
