frr version 10.6
frr defaults traditional
hostname openpe-tor
log stdout informational
!
interface eth0
 ip address 10.0.0.20/32
 ipv6 address fc00:100::20/128
 ipv6 address fc00:0:20::1/128
 ipv6 address fd00:20::1/128
 ipv6 router isis PE
 isis circuit-type level-1
exit
!
vrf red
exit-vrf
!
router bgp 65500
 bgp router-id 10.0.0.20
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 no bgp network import-check
 bgp log-neighbor-changes
 neighbor PE-NODES peer-group
 neighbor PE-NODES remote-as 65500
 neighbor PE-NODES update-source fc00:0:20::1
 bgp listen range fd00::/64 peer-group PE-NODES
 segment-routing srv6
  locator MAIN
 exit
 address-family ipv4 vpn
  neighbor PE-NODES activate
 exit-address-family
 address-family ipv6 vpn
  neighbor PE-NODES activate
 exit-address-family
exit
!
router bgp 65500 vrf red
 bgp router-id 10.0.0.20
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 no bgp network import-check
 sid vpn per-vrf export auto
 address-family ipv4 unicast
  redistribute connected
  redistribute static
  rd vpn export 10.0.0.20:2
  rt vpn both 65500:2
  export vpn
  import vpn
 exit-address-family
 address-family ipv6 unicast
  redistribute connected
  redistribute static
  rd vpn export 10.0.0.20:2
  rt vpn both 65500:2
  export vpn
  import vpn
 exit-address-family
exit
!
ip route 10.100.0.1/32 10.200.0.2 vrf red
ip route 10.10.20.1/32 10.200.0.2 vrf red
ipv6 route fd00:100::1/128 fd00:200::2 vrf red
ipv6 route fc00:10:20::1/128 fd00:200::2 vrf red
!
router isis PE
 is-type level-1
 net 49.0001.0000.0000.0020.00
 topology ipv6-unicast
 segment-routing srv6
  locator MAIN
 exit
exit
!
segment-routing
 srv6
  encapsulation
   source-address fd00:20::1
  exit
  locators
   locator MAIN
    prefix fd00:20::/48 block-len 32 node-len 16 func-bits 16
    behavior usid
   exit
  exit
 exit
exit
!
ip forwarding
ipv6 forwarding
!
end
