# agent-config.yaml - Per-node hardware configuration
#
apiVersion: v1alpha1
metadata:
  name: sno-lab
  namespace: cluster0
additionalNTPSources:
- 10.100.0.1
rendezvousIP: 192.168.110.2
hosts:
- hostname: master-0.sno-lab.example.com
  rootDeviceHints:
    deviceName: /dev/sda
  interfaces:
  - name: ens3f0np0
    macAddress: B8:E9:24:16:09:AC
  - name: eno12399np0
    macAddress: B8:E9:24:8F:D8:B6
  networkConfig:
    interfaces:
    - name: eno12399np0
      state: up
      type: ethernet
      ipv4:
        enabled: false
      ipv6:
        enabled: false
      ethernet:
        sr-iov:
          total-vfs: 16
          vfs:
          - id: 0 # underlay0
            vlan-id: 0
            spoof-check: false
            trust: true
          - id: 1 # host
            vlan-id: 42
            spoof-check: false
            trust: true
 
    - name: eno12399v0 # underlay0 (grout)
      type: ethernet
      state: up

    - name: eno12399v1
      type: ethernet
      state: up
      mtu: 1400
      ipv4:
        enabled: true
        auto-dns: false
        address:
        - ip: 192.168.110.2
          prefix-length: 24
        dhcp: false
      ipv6:
        enabled: true
        auto-dns: false
        address:
        - ip: fd00:110::2
          prefix-length: 64
        dhcp: false

    - {name: eno12399v2, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v3, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v4, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v5, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v6, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v7, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v8, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v9, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v10, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v11, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v12, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v13, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v14, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v15, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}

    - name: eno12409np1
      state: down
      type: ethernet


    - name: bond1
      state: down
      type: bond
      link-aggregation:
        mode: 802.3ad
        options: {"miimon": 100}
        ports:
          - ens3f0np0
          - ens3f1np1
    - name: ens3f0np0
      state: down
      type: ethernet
    - name: ens3f1np1
      state: down
      type: ethernet
    - name: bond1.16
      state: up
      type: vlan
      wait-ip: ipv4
      ipv4:
        address:
          - ip: 192.168.21.31
            prefix-length: 25
        dhcp: false
        enabled: true
      vlan:
        base-iface: bond1
        id: 16

    dns-resolver:
      config:
        server:
        - 192.168.110.1
        - fd00:110::1
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 192.168.110.1
        next-hop-interface: eno12399v1
      - destination: ::/0
        next-hop-address: fd00:110::1
        next-hop-interface: eno12399v1
- hostname: master-1.sno-lab.example.com
  interfaces:
  - name: ens3f0np0
    macAddress: B8:E9:24:16:0E:0C
  - name: eno12399np0
    macAddress: B8:E9:24:8F:DB:EC
  networkConfig:
    interfaces:
    - name: eno12399np0
      state: up
      type: ethernet
      ipv4:
        enabled: false
      ipv6:
        enabled: false
      ethernet:
        sr-iov:
          total-vfs: 16
          vfs:
          - id: 0 # underlay0
            vlan-id: 0
            spoof-check: false
            trust: true
          - id: 1 # host
            vlan-id: 42
            spoof-check: false
            trust: true
 
    - name: eno12399v0 # underlay0 (grout)
      type: ethernet
      state: up

    - name: eno12399v1
      type: ethernet
      state: up
      mtu: 1400
      ipv4:
        enabled: true
        auto-dns: false
        address:
        - ip: 192.168.110.3
          prefix-length: 24
        dhcp: false
      ipv6:
        enabled: true
        auto-dns: false
        address:
        - ip: fd00:110::3
          prefix-length: 64
        dhcp: false

    - {name: eno12399v2, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v3, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v4, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v5, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v6, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v7, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v8, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v9, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v10, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v11, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v12, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v13, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v14, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v15, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}

    - name: eno12409np1
      state: down
      type: ethernet


    - name: bond1
      state: down
      type: bond
      link-aggregation:
        mode: 802.3ad
        options: {"miimon": 100}
        ports:
          - ens3f0np0
          - ens3f1np1
    - name: ens3f0np0
      state: down
      type: ethernet
    - name: ens3f1np1
      state: down
      type: ethernet
    - name: bond1.16
      state: up
      type: vlan
      wait-ip: ipv4
      ipv4:
        address:
          - ip: 192.168.21.32
            prefix-length: 25
        dhcp: false
        enabled: true
      vlan:
        base-iface: bond1
        id: 16

    dns-resolver:
      config:
        server:
        - 192.168.110.1
        - fd00:110::1
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 192.168.110.1
        next-hop-interface: eno12399v1
      - destination: ::/0
        next-hop-address: fd00:110::1
        next-hop-interface: eno12399v1
- hostname: master-2.sno-lab.example.com
  interfaces:
  - name: ens3f0np0
    macAddress: B8:E9:24:16:09:84
  - name: eno12399np0
    macAddress: B8:E9:24:8F:D8:9E
  networkConfig:
    interfaces:
    - name: eno12399np0
      state: up
      type: ethernet
      ipv4:
        enabled: false
      ipv6:
        enabled: false
      ethernet:
        sr-iov:
          total-vfs: 16
          vfs:
          - id: 0 # underlay0
            vlan-id: 0
            spoof-check: false
            trust: true
          - id: 1 # host
            vlan-id: 42
            spoof-check: false
            trust: true
 
    - name: eno12399v0 # underlay0 (grout)
      type: ethernet
      state: up

    - name: eno12399v1
      type: ethernet
      state: up
      mtu: 1400
      ipv4:
        enabled: true
        auto-dns: false
        address:
        - ip: 192.168.110.4
          prefix-length: 24
        dhcp: false
      ipv6:
        enabled: true
        auto-dns: false
        address:
        - ip: fd00:110::4
          prefix-length: 64
        dhcp: false

    - {name: eno12399v2, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v3, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v4, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v5, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v6, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v7, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v8, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v9, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v10, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v11, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v12, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v13, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v14, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}
    - {name: eno12399v15, type: ethernet, state: up, ipv4: {enabled: false}, ipv6: {enabled: false}}

    - name: eno12409np1
      state: down
      type: ethernet

    - name: bond1
      state: down
      type: bond
      link-aggregation:
        mode: 802.3ad
        options: {"miimon": 100}
        ports:
          - ens3f0np0
          - ens3f1np1
    - name: ens3f0np0
      state: down
      type: ethernet
    - name: ens3f1np1
      state: down
      type: ethernet
    - name: bond1.16
      state: up
      type: vlan
      wait-ip: ipv4
      ipv4:
        address:
          - ip: 192.168.21.33
            prefix-length: 25
        dhcp: false
        enabled: true
      vlan:
        base-iface: bond1
        id: 16

    dns-resolver:
      config:
        server:
        - 192.168.110.1
        - fd00:110::1
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 192.168.110.1
        next-hop-interface: eno12399v1
      - destination: ::/0
        next-hop-address: fd00:110::1
        next-hop-interface: eno12399v1
