#!/bin/bash
# perouter-host-dispatch.sh - Derive OpenPERouter addressing from host VF IP
#
# Called by NM dispatch post-activation on the host VF. Derives all
# addresses from the host IP's last octet and writes vpn-setup.vars.
#
# Usage: perouter-host-dispatch.sh <interface> <action>
#   Called by NetworkManager dispatcher with interface name and action.

set -euo pipefail

die() { echo "error: $*" >&2; exit 1; }

iface="$1"
action="${2:-up}"

[ "$action" = "up" ] || exit 0

source /etc/openperouter/openperouter.env

# Wait for the interface to get an IPv4 address.
HOST_IP=""
HOST_IP6=""
for _ in $(seq 60); do
	HOST_IP=$(ip -4 -o addr show "$iface" scope global 2>/dev/null | awk '{print $4; exit}')
	HOST_IP6=$(ip -6 -o addr show "$iface" scope global 2>/dev/null | awk '{print $4; exit}')
	[ -n "$HOST_IP" ] && break
	sleep 1
done
if [ -z "$HOST_IP" ]; then
	die "no IPv4 on $iface after 60s"
fi

LAST_OCTET=$(echo "$HOST_IP" | sed 's,.*/,,; s,.*\.,,' )
ROUTER_ID=$(printf "$ROUTER_ID_FMT" "$LAST_OCTET")

# Derive host VF VLAN from the PF's VF config
HOST_VLAN=0
vf_pci=$(readlink -ve /sys/class/net/$iface/device)
pf_name=$(basename /sys/class/net/$iface/device/physfn/net/*)
for vfn in /sys/class/net/$pf_name/device/virtfn*; do
	if [ "$(readlink -ve $vfn)" = "$vf_pci" ]; then
		vf_idx=$(basename "$vfn" | sed 's/virtfn//')
		HOST_VLAN=$(ip link show "$pf_name" |
			sed -En "s/.*vf $vf_idx.*vlan ([0-9]+).*/\\1/p")
		break
	fi
done

VARS_FILE=/var/lib/openperouter/vpn-setup.vars
mkdir -p $(dirname $VARS_FILE)

# Derive all addresses from format strings in openperouter.env
cat > $VARS_FILE <<EOF
# Generated by perouter-host-dispatch.sh on $(date +'%Y-%m-%d %H:%M:%S')
NODE_NAME="$(hostname)"
LAST_OCTET="$LAST_OCTET"
ROUTER_ID="$ROUTER_ID"
VTEP_IP="$ROUTER_ID"
HOST_IP="$HOST_IP"
HOST_IP6="$HOST_IP6"
HOST_SUBNET="$(ip -4 route list dev "$iface" scope link proto kernel | awk '{print $1; exit}')"
HOST_SUBNET_V6="$(ip -6 route list dev "$iface" proto kernel | awk '{print $1; exit}')"
HOST_VLAN=$HOST_VLAN
LOOPBACK_V6="$(printf "$LOOPBACK_V6_FMT" "$LAST_OCTET")"
SRV6_SOURCE="$(printf "$SRV6_SOURCE_FMT" "$LAST_OCTET")"
SRV6_PREFIX="$(printf "$SRV6_PREFIX_FMT" "$LAST_OCTET")"
SRV6_NODE_ID="$LAST_OCTET"
UNDERLAY_V6="$(printf "$UNDERLAY_V6_FMT" "$LAST_OCTET")"
ISIS_NET="$ISIS_AREA.0000.0000.$(printf %04d $LAST_OCTET).00"
EOF

chmod 644 $VARS_FILE

# Write node-config.yaml for the controller
NODE_CONFIG=/var/lib/openperouter/node-config.yaml
mkdir -p $(dirname $NODE_CONFIG)
cat > $NODE_CONFIG <<EOF
nodeIndex:
  index: $LAST_OCTET
logLevel: info
EOF

echo "perouter-host-dispatch: wrote $VARS_FILE + $NODE_CONFIG (LAST_OCTET=$LAST_OCTET)"
